export const GET_SLACK_USERS="GET_SLACK_USERS";
export const GET_SLACK_USERS_SUCCESS="GET_SLACK_USERS_SUCCESS";
export const GET_GOOGLE_AUTH="GET_GOOGLE_AUTH";
export const GET_GOOGLE_AUTH_SUCCESS="GET_GOOGLE_AUTH_SUCCESS";
export const SEND_TOKEN="SEND_TOKEN";